[package]
name = "embedded-bdf"
version = "0.1.0"
authors = ["Ralf Fuest <mail@rfuest.de>"]
edition = "2018"

[dependencies]
embedded-graphics = "0.7.0-alpha.3"
embedded-bdf-macros = { path = "../embedded-bdf-macros" }

[dev-dependencies]
embedded-graphics-simulator = "0.3.0-alpha.2"
