[package]
name = "test-bdf-parser"
version = "0.1.0"
authors = ["Ralf Fuest <mail@rfuest.de>"]
edition = "2018"

[dependencies]
bdf-parser = { path = "../../bdf-parser" }
clap = { version = "3.0.0-rc.7", features = [ "derive" ] }
